version: "3.8"

services:
  frontend:
    build:
      context: ./blog-frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./blog-frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:ozi@db:5432/blogdb

  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ozi
      POSTGRES_DB: blogdb

volumes:
  pgdata:
