version: "3.8"

services:
  frontend:
    volumes:
      - ./blog-frontend:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]

  backend:
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]
